/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { HopitalWhereUniqueInput } from "../../hopital/base/HopitalWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { IntFilter } from "../../util/IntFilter";
import { LigneOrdonnanceListRelationFilter } from "../../ligneOrdonnance/base/LigneOrdonnanceListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { RetraitStockListRelationFilter } from "../../retraitStock/base/RetraitStockListRelationFilter";

@InputType()
class MedicamentWhereInput {
  @ApiProperty({
    required: false,
    type: () => HopitalWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => HopitalWhereUniqueInput)
  @IsOptional()
  @Field(() => HopitalWhereUniqueInput, {
    nullable: true,
  })
  hopital?: HopitalWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  id?: IntFilter;

  @ApiProperty({
    required: false,
    type: () => LigneOrdonnanceListRelationFilter,
  })
  @ValidateNested()
  @Type(() => LigneOrdonnanceListRelationFilter)
  @IsOptional()
  @Field(() => LigneOrdonnanceListRelationFilter, {
    nullable: true,
  })
  lignes?: LigneOrdonnanceListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  nom?: StringFilter;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  quantite?: IntFilter;

  @ApiProperty({
    required: false,
    type: () => RetraitStockListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RetraitStockListRelationFilter)
  @IsOptional()
  @Field(() => RetraitStockListRelationFilter, {
    nullable: true,
  })
  retraits?: RetraitStockListRelationFilter;
}

export { MedicamentWhereInput as MedicamentWhereInput };
