/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { UtilisateurWhereUniqueInput } from "../../utilisateur/base/UtilisateurWhereUniqueInput";
import { DossierMedicalListRelationFilter } from "../../dossierMedical/base/DossierMedicalListRelationFilter";
import { HopitalWhereUniqueInput } from "../../hopital/base/HopitalWhereUniqueInput";
import { IntFilter } from "../../util/IntFilter";
import { RendezVousListRelationFilter } from "../../rendezVous/base/RendezVousListRelationFilter";
import { EnumPatientSexe } from "./EnumPatientSexe";

@InputType()
class PatientWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  adresse?: StringFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  createdAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => UtilisateurWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UtilisateurWhereUniqueInput)
  @IsOptional()
  @Field(() => UtilisateurWhereUniqueInput, {
    nullable: true,
  })
  createur?: UtilisateurWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  dateNaissance?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => DossierMedicalListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DossierMedicalListRelationFilter)
  @IsOptional()
  @Field(() => DossierMedicalListRelationFilter, {
    nullable: true,
  })
  dossiers?: DossierMedicalListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => HopitalWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => HopitalWhereUniqueInput)
  @IsOptional()
  @Field(() => HopitalWhereUniqueInput, {
    nullable: true,
  })
  hopital?: HopitalWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  id?: IntFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  nom?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  prenom?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => RendezVousListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RendezVousListRelationFilter)
  @IsOptional()
  @Field(() => RendezVousListRelationFilter, {
    nullable: true,
  })
  rendezVous?: RendezVousListRelationFilter;

  @ApiProperty({
    required: false,
    enum: EnumPatientSexe,
  })
  @IsEnum(EnumPatientSexe)
  @IsOptional()
  @Field(() => EnumPatientSexe, {
    nullable: true,
  })
  sexe?: "MASCULIN" | "FEMININ";

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  telephone?: StringFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  updatedAt?: DateTimeFilter;
}

export { PatientWhereInput as PatientWhereInput };
