/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  ValidateNested,
  IsDate,
  IsOptional,
  IsEnum,
} from "class-validator";
import { UtilisateurWhereUniqueInput } from "../../utilisateur/base/UtilisateurWhereUniqueInput";
import { Type } from "class-transformer";
import { DossierMedicalCreateNestedManyWithoutPatientsInput } from "./DossierMedicalCreateNestedManyWithoutPatientsInput";
import { HopitalWhereUniqueInput } from "../../hopital/base/HopitalWhereUniqueInput";
import { RendezVousCreateNestedManyWithoutPatientsInput } from "./RendezVousCreateNestedManyWithoutPatientsInput";
import { EnumPatientSexe } from "./EnumPatientSexe";

@InputType()
class PatientCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  adresse!: string;

  @ApiProperty({
    required: true,
    type: () => UtilisateurWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UtilisateurWhereUniqueInput)
  @Field(() => UtilisateurWhereUniqueInput)
  createur!: UtilisateurWhereUniqueInput;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  dateNaissance!: Date;

  @ApiProperty({
    required: false,
    type: () => DossierMedicalCreateNestedManyWithoutPatientsInput,
  })
  @ValidateNested()
  @Type(() => DossierMedicalCreateNestedManyWithoutPatientsInput)
  @IsOptional()
  @Field(() => DossierMedicalCreateNestedManyWithoutPatientsInput, {
    nullable: true,
  })
  dossiers?: DossierMedicalCreateNestedManyWithoutPatientsInput;

  @ApiProperty({
    required: true,
    type: () => HopitalWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => HopitalWhereUniqueInput)
  @Field(() => HopitalWhereUniqueInput)
  hopital!: HopitalWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  nom!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  prenom!: string;

  @ApiProperty({
    required: false,
    type: () => RendezVousCreateNestedManyWithoutPatientsInput,
  })
  @ValidateNested()
  @Type(() => RendezVousCreateNestedManyWithoutPatientsInput)
  @IsOptional()
  @Field(() => RendezVousCreateNestedManyWithoutPatientsInput, {
    nullable: true,
  })
  rendezVous?: RendezVousCreateNestedManyWithoutPatientsInput;

  @ApiProperty({
    required: true,
    enum: EnumPatientSexe,
  })
  @IsEnum(EnumPatientSexe)
  @Field(() => EnumPatientSexe)
  sexe!: "MASCULIN" | "FEMININ";

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  telephone!: string;
}

export { PatientCreateInput as PatientCreateInput };
