/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Patient } from "./Patient";
import { PatientCountArgs } from "./PatientCountArgs";
import { PatientFindManyArgs } from "./PatientFindManyArgs";
import { PatientFindUniqueArgs } from "./PatientFindUniqueArgs";
import { CreatePatientArgs } from "./CreatePatientArgs";
import { UpdatePatientArgs } from "./UpdatePatientArgs";
import { DeletePatientArgs } from "./DeletePatientArgs";
import { DossierMedicalFindManyArgs } from "../../dossierMedical/base/DossierMedicalFindManyArgs";
import { DossierMedical } from "../../dossierMedical/base/DossierMedical";
import { RendezVousFindManyArgs } from "../../rendezVous/base/RendezVousFindManyArgs";
import { RendezVous } from "../../rendezVous/base/RendezVous";
import { Utilisateur } from "../../utilisateur/base/Utilisateur";
import { Hopital } from "../../hopital/base/Hopital";
import { PatientService } from "../patient.service";
@graphql.Resolver(() => Patient)
export class PatientResolverBase {
  constructor(protected readonly service: PatientService) {}

  async _patientsMeta(
    @graphql.Args() args: PatientCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Patient])
  async patients(
    @graphql.Args() args: PatientFindManyArgs
  ): Promise<Patient[]> {
    return this.service.patients(args);
  }

  @graphql.Query(() => Patient, { nullable: true })
  async patient(
    @graphql.Args() args: PatientFindUniqueArgs
  ): Promise<Patient | null> {
    const result = await this.service.patient(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Patient)
  async createPatient(
    @graphql.Args() args: CreatePatientArgs
  ): Promise<Patient> {
    return await this.service.createPatient({
      ...args,
      data: {
        ...args.data,

        createur: {
          connect: args.data.createur,
        },

        hopital: {
          connect: args.data.hopital,
        },
      },
    });
  }

  @graphql.Mutation(() => Patient)
  async updatePatient(
    @graphql.Args() args: UpdatePatientArgs
  ): Promise<Patient | null> {
    try {
      return await this.service.updatePatient({
        ...args,
        data: {
          ...args.data,

          createur: {
            connect: args.data.createur,
          },

          hopital: {
            connect: args.data.hopital,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Patient)
  async deletePatient(
    @graphql.Args() args: DeletePatientArgs
  ): Promise<Patient | null> {
    try {
      return await this.service.deletePatient(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [DossierMedical], { name: "dossiers" })
  async findDossiers(
    @graphql.Parent() parent: Patient,
    @graphql.Args() args: DossierMedicalFindManyArgs
  ): Promise<DossierMedical[]> {
    const results = await this.service.findDossiers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [RendezVous], { name: "rendezVous" })
  async findRendezVous(
    @graphql.Parent() parent: Patient,
    @graphql.Args() args: RendezVousFindManyArgs
  ): Promise<RendezVous[]> {
    const results = await this.service.findRendezVous(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Utilisateur, {
    nullable: true,
    name: "createur",
  })
  async getCreateur(
    @graphql.Parent() parent: Patient
  ): Promise<Utilisateur | null> {
    const result = await this.service.getCreateur(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Hopital, {
    nullable: true,
    name: "hopital",
  })
  async getHopital(@graphql.Parent() parent: Patient): Promise<Hopital | null> {
    const result = await this.service.getHopital(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
