/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { DossierMedicalWhereUniqueInput } from "../../dossierMedical/base/DossierMedicalWhereUniqueInput";
import { IntFilter } from "../../util/IntFilter";
import { LigneOrdonnanceListRelationFilter } from "../../ligneOrdonnance/base/LigneOrdonnanceListRelationFilter";
import { EnumOrdonnanceStatut } from "./EnumOrdonnanceStatut";
import { UtilisateurWhereUniqueInput } from "../../utilisateur/base/UtilisateurWhereUniqueInput";

@InputType()
class OrdonnanceWhereInput {
  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  createdAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => DossierMedicalWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DossierMedicalWhereUniqueInput)
  @IsOptional()
  @Field(() => DossierMedicalWhereUniqueInput, {
    nullable: true,
  })
  dossier?: DossierMedicalWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  id?: IntFilter;

  @ApiProperty({
    required: false,
    type: () => LigneOrdonnanceListRelationFilter,
  })
  @ValidateNested()
  @Type(() => LigneOrdonnanceListRelationFilter)
  @IsOptional()
  @Field(() => LigneOrdonnanceListRelationFilter, {
    nullable: true,
  })
  lignes?: LigneOrdonnanceListRelationFilter;

  @ApiProperty({
    required: false,
    enum: EnumOrdonnanceStatut,
  })
  @IsEnum(EnumOrdonnanceStatut)
  @IsOptional()
  @Field(() => EnumOrdonnanceStatut, {
    nullable: true,
  })
  statut?: "EN_ATTENTE" | "VALIDEE" | "REJETEE";

  @ApiProperty({
    required: false,
    type: () => UtilisateurWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UtilisateurWhereUniqueInput)
  @IsOptional()
  @Field(() => UtilisateurWhereUniqueInput, {
    nullable: true,
  })
  utilisateur?: UtilisateurWhereUniqueInput;
}

export { OrdonnanceWhereInput as OrdonnanceWhereInput };
