/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { EmployeService } from "../employe.service";
import { EmployeCreateInput } from "./EmployeCreateInput";
import { Employe } from "./Employe";
import { EmployeFindManyArgs } from "./EmployeFindManyArgs";
import { EmployeWhereUniqueInput } from "./EmployeWhereUniqueInput";
import { EmployeUpdateInput } from "./EmployeUpdateInput";

export class EmployeControllerBase {
  constructor(protected readonly service: EmployeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Employe })
  async createEmploye(
    @common.Body() data: EmployeCreateInput
  ): Promise<Employe> {
    return await this.service.createEmploye({
      data: {
        ...data,

        hopital: {
          connect: data.hopital,
        },
      },
      select: {
        adresse: true,
        agents: true,
        contactUrgence: true,
        createdAt: true,
        email: true,

        hopital: {
          select: {
            id: true,
          },
        },

        id: true,
        nom: true,
        poste: true,
        prenom: true,
        sexe: true,
        statut: true,
        telephone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Employe] })
  @ApiNestedQuery(EmployeFindManyArgs)
  async employes(@common.Req() request: Request): Promise<Employe[]> {
    const args = plainToClass(EmployeFindManyArgs, request.query);
    return this.service.employes({
      ...args,
      select: {
        adresse: true,
        agents: true,
        contactUrgence: true,
        createdAt: true,
        email: true,

        hopital: {
          select: {
            id: true,
          },
        },

        id: true,
        nom: true,
        poste: true,
        prenom: true,
        sexe: true,
        statut: true,
        telephone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Employe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async employe(
    @common.Param() params: EmployeWhereUniqueInput
  ): Promise<Employe | null> {
    const result = await this.service.employe({
      where: params,
      select: {
        adresse: true,
        agents: true,
        contactUrgence: true,
        createdAt: true,
        email: true,

        hopital: {
          select: {
            id: true,
          },
        },

        id: true,
        nom: true,
        poste: true,
        prenom: true,
        sexe: true,
        statut: true,
        telephone: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Employe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateEmploye(
    @common.Param() params: EmployeWhereUniqueInput,
    @common.Body() data: EmployeUpdateInput
  ): Promise<Employe | null> {
    try {
      return await this.service.updateEmploye({
        where: params,
        data: {
          ...data,

          hopital: {
            connect: data.hopital,
          },
        },
        select: {
          adresse: true,
          agents: true,
          contactUrgence: true,
          createdAt: true,
          email: true,

          hopital: {
            select: {
              id: true,
            },
          },

          id: true,
          nom: true,
          poste: true,
          prenom: true,
          sexe: true,
          statut: true,
          telephone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Employe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteEmploye(
    @common.Param() params: EmployeWhereUniqueInput
  ): Promise<Employe | null> {
    try {
      return await this.service.deleteEmploye({
        where: params,
        select: {
          adresse: true,
          agents: true,
          contactUrgence: true,
          createdAt: true,
          email: true,

          hopital: {
            select: {
              id: true,
            },
          },

          id: true,
          nom: true,
          poste: true,
          prenom: true,
          sexe: true,
          statut: true,
          telephone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
