/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { RetraitStockWhereInput } from "./RetraitStockWhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { RetraitStockOrderByInput } from "./RetraitStockOrderByInput";

@ArgsType()
class RetraitStockFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => RetraitStockWhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => RetraitStockWhereInput, { nullable: true })
  @Type(() => RetraitStockWhereInput)
  where?: RetraitStockWhereInput;

  @ApiProperty({
    required: false,
    type: [RetraitStockOrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [RetraitStockOrderByInput], { nullable: true })
  @Type(() => RetraitStockOrderByInput)
  orderBy?: Array<RetraitStockOrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { RetraitStockFindManyArgs as RetraitStockFindManyArgs };
