/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Utilisateur } from "./Utilisateur";
import { UtilisateurCountArgs } from "./UtilisateurCountArgs";
import { UtilisateurFindManyArgs } from "./UtilisateurFindManyArgs";
import { UtilisateurFindUniqueArgs } from "./UtilisateurFindUniqueArgs";
import { CreateUtilisateurArgs } from "./CreateUtilisateurArgs";
import { UpdateUtilisateurArgs } from "./UpdateUtilisateurArgs";
import { DeleteUtilisateurArgs } from "./DeleteUtilisateurArgs";
import { DepenseFindManyArgs } from "../../depense/base/DepenseFindManyArgs";
import { Depense } from "../../depense/base/Depense";
import { DossierMedicalFindManyArgs } from "../../dossierMedical/base/DossierMedicalFindManyArgs";
import { DossierMedical } from "../../dossierMedical/base/DossierMedical";
import { HistoriqueActionFindManyArgs } from "../../historiqueAction/base/HistoriqueActionFindManyArgs";
import { HistoriqueAction } from "../../historiqueAction/base/HistoriqueAction";
import { OrdonnanceFindManyArgs } from "../../ordonnance/base/OrdonnanceFindManyArgs";
import { Ordonnance } from "../../ordonnance/base/Ordonnance";
import { PatientFindManyArgs } from "../../patient/base/PatientFindManyArgs";
import { Patient } from "../../patient/base/Patient";
import { RendezVousFindManyArgs } from "../../rendezVous/base/RendezVousFindManyArgs";
import { RendezVous } from "../../rendezVous/base/RendezVous";
import { RetraitStockFindManyArgs } from "../../retraitStock/base/RetraitStockFindManyArgs";
import { RetraitStock } from "../../retraitStock/base/RetraitStock";
import { Dgtcp } from "../../dgtcp/base/Dgtcp";
import { Hopital } from "../../hopital/base/Hopital";
import { UtilisateurService } from "../utilisateur.service";
@graphql.Resolver(() => Utilisateur)
export class UtilisateurResolverBase {
  constructor(protected readonly service: UtilisateurService) {}

  async _utilisateursMeta(
    @graphql.Args() args: UtilisateurCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Utilisateur])
  async utilisateurs(
    @graphql.Args() args: UtilisateurFindManyArgs
  ): Promise<Utilisateur[]> {
    return this.service.utilisateurs(args);
  }

  @graphql.Query(() => Utilisateur, { nullable: true })
  async utilisateur(
    @graphql.Args() args: UtilisateurFindUniqueArgs
  ): Promise<Utilisateur | null> {
    const result = await this.service.utilisateur(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Utilisateur)
  async createUtilisateur(
    @graphql.Args() args: CreateUtilisateurArgs
  ): Promise<Utilisateur> {
    return await this.service.createUtilisateur({
      ...args,
      data: {
        ...args.data,

        dgtcp: args.data.dgtcp
          ? {
              connect: args.data.dgtcp,
            }
          : undefined,

        hopital: args.data.hopital
          ? {
              connect: args.data.hopital,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Utilisateur)
  async updateUtilisateur(
    @graphql.Args() args: UpdateUtilisateurArgs
  ): Promise<Utilisateur | null> {
    try {
      return await this.service.updateUtilisateur({
        ...args,
        data: {
          ...args.data,

          dgtcp: args.data.dgtcp
            ? {
                connect: args.data.dgtcp,
              }
            : undefined,

          hopital: args.data.hopital
            ? {
                connect: args.data.hopital,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Utilisateur)
  async deleteUtilisateur(
    @graphql.Args() args: DeleteUtilisateurArgs
  ): Promise<Utilisateur | null> {
    try {
      return await this.service.deleteUtilisateur(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Depense], { name: "depenses" })
  async findDepenses(
    @graphql.Parent() parent: Utilisateur,
    @graphql.Args() args: DepenseFindManyArgs
  ): Promise<Depense[]> {
    const results = await this.service.findDepenses(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [DossierMedical], { name: "dossiersMedicaux" })
  async findDossiersMedicaux(
    @graphql.Parent() parent: Utilisateur,
    @graphql.Args() args: DossierMedicalFindManyArgs
  ): Promise<DossierMedical[]> {
    const results = await this.service.findDossiersMedicaux(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [HistoriqueAction], { name: "historiques" })
  async findHistoriques(
    @graphql.Parent() parent: Utilisateur,
    @graphql.Args() args: HistoriqueActionFindManyArgs
  ): Promise<HistoriqueAction[]> {
    const results = await this.service.findHistoriques(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Ordonnance], { name: "ordonnances" })
  async findOrdonnances(
    @graphql.Parent() parent: Utilisateur,
    @graphql.Args() args: OrdonnanceFindManyArgs
  ): Promise<Ordonnance[]> {
    const results = await this.service.findOrdonnances(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Patient], { name: "patients" })
  async findPatients(
    @graphql.Parent() parent: Utilisateur,
    @graphql.Args() args: PatientFindManyArgs
  ): Promise<Patient[]> {
    const results = await this.service.findPatients(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [RendezVous], { name: "rendezVous" })
  async findRendezVous(
    @graphql.Parent() parent: Utilisateur,
    @graphql.Args() args: RendezVousFindManyArgs
  ): Promise<RendezVous[]> {
    const results = await this.service.findRendezVous(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [RetraitStock], { name: "retraitsStock" })
  async findRetraitsStock(
    @graphql.Parent() parent: Utilisateur,
    @graphql.Args() args: RetraitStockFindManyArgs
  ): Promise<RetraitStock[]> {
    const results = await this.service.findRetraitsStock(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Dgtcp, {
    nullable: true,
    name: "dgtcp",
  })
  async getDgtcp(@graphql.Parent() parent: Utilisateur): Promise<Dgtcp | null> {
    const result = await this.service.getDgtcp(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Hopital, {
    nullable: true,
    name: "hopital",
  })
  async getHopital(
    @graphql.Parent() parent: Utilisateur
  ): Promise<Hopital | null> {
    const result = await this.service.getHopital(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
