/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DepenseUpdateManyWithoutUtilisateursInput } from "./DepenseUpdateManyWithoutUtilisateursInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { DgtcpWhereUniqueInput } from "../../dgtcp/base/DgtcpWhereUniqueInput";
import { DossierMedicalUpdateManyWithoutUtilisateursInput } from "./DossierMedicalUpdateManyWithoutUtilisateursInput";
import { HistoriqueActionUpdateManyWithoutUtilisateursInput } from "./HistoriqueActionUpdateManyWithoutUtilisateursInput";
import { HopitalWhereUniqueInput } from "../../hopital/base/HopitalWhereUniqueInput";
import { OrdonnanceUpdateManyWithoutUtilisateursInput } from "./OrdonnanceUpdateManyWithoutUtilisateursInput";
import { PatientUpdateManyWithoutUtilisateursInput } from "./PatientUpdateManyWithoutUtilisateursInput";
import { RendezVousUpdateManyWithoutUtilisateursInput } from "./RendezVousUpdateManyWithoutUtilisateursInput";
import { RetraitStockUpdateManyWithoutUtilisateursInput } from "./RetraitStockUpdateManyWithoutUtilisateursInput";
import { EnumUtilisateurRole } from "./EnumUtilisateurRole";
import { EnumUtilisateurStatut } from "./EnumUtilisateurStatut";

@InputType()
class UtilisateurUpdateInput {
  @ApiProperty({
    required: false,
    type: () => DepenseUpdateManyWithoutUtilisateursInput,
  })
  @ValidateNested()
  @Type(() => DepenseUpdateManyWithoutUtilisateursInput)
  @IsOptional()
  @Field(() => DepenseUpdateManyWithoutUtilisateursInput, {
    nullable: true,
  })
  depenses?: DepenseUpdateManyWithoutUtilisateursInput;

  @ApiProperty({
    required: false,
    type: () => DgtcpWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DgtcpWhereUniqueInput)
  @IsOptional()
  @Field(() => DgtcpWhereUniqueInput, {
    nullable: true,
  })
  dgtcp?: DgtcpWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => DossierMedicalUpdateManyWithoutUtilisateursInput,
  })
  @ValidateNested()
  @Type(() => DossierMedicalUpdateManyWithoutUtilisateursInput)
  @IsOptional()
  @Field(() => DossierMedicalUpdateManyWithoutUtilisateursInput, {
    nullable: true,
  })
  dossiersMedicaux?: DossierMedicalUpdateManyWithoutUtilisateursInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string;

  @ApiProperty({
    required: false,
    type: () => HistoriqueActionUpdateManyWithoutUtilisateursInput,
  })
  @ValidateNested()
  @Type(() => HistoriqueActionUpdateManyWithoutUtilisateursInput)
  @IsOptional()
  @Field(() => HistoriqueActionUpdateManyWithoutUtilisateursInput, {
    nullable: true,
  })
  historiques?: HistoriqueActionUpdateManyWithoutUtilisateursInput;

  @ApiProperty({
    required: false,
    type: () => HopitalWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => HopitalWhereUniqueInput)
  @IsOptional()
  @Field(() => HopitalWhereUniqueInput, {
    nullable: true,
  })
  hopital?: HopitalWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  motDePasse?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nom?: string;

  @ApiProperty({
    required: false,
    type: () => OrdonnanceUpdateManyWithoutUtilisateursInput,
  })
  @ValidateNested()
  @Type(() => OrdonnanceUpdateManyWithoutUtilisateursInput)
  @IsOptional()
  @Field(() => OrdonnanceUpdateManyWithoutUtilisateursInput, {
    nullable: true,
  })
  ordonnances?: OrdonnanceUpdateManyWithoutUtilisateursInput;

  @ApiProperty({
    required: false,
    type: () => PatientUpdateManyWithoutUtilisateursInput,
  })
  @ValidateNested()
  @Type(() => PatientUpdateManyWithoutUtilisateursInput)
  @IsOptional()
  @Field(() => PatientUpdateManyWithoutUtilisateursInput, {
    nullable: true,
  })
  patients?: PatientUpdateManyWithoutUtilisateursInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  prenom?: string;

  @ApiProperty({
    required: false,
    type: () => RendezVousUpdateManyWithoutUtilisateursInput,
  })
  @ValidateNested()
  @Type(() => RendezVousUpdateManyWithoutUtilisateursInput)
  @IsOptional()
  @Field(() => RendezVousUpdateManyWithoutUtilisateursInput, {
    nullable: true,
  })
  rendezVous?: RendezVousUpdateManyWithoutUtilisateursInput;

  @ApiProperty({
    required: false,
    type: () => RetraitStockUpdateManyWithoutUtilisateursInput,
  })
  @ValidateNested()
  @Type(() => RetraitStockUpdateManyWithoutUtilisateursInput)
  @IsOptional()
  @Field(() => RetraitStockUpdateManyWithoutUtilisateursInput, {
    nullable: true,
  })
  retraitsStock?: RetraitStockUpdateManyWithoutUtilisateursInput;

  @ApiProperty({
    required: false,
    enum: EnumUtilisateurRole,
  })
  @IsEnum(EnumUtilisateurRole)
  @IsOptional()
  @Field(() => EnumUtilisateurRole, {
    nullable: true,
  })
  role?:
    | "SUPER_ADMIN"
    | "ADMIN"
    | "MEDECIN"
    | "PHARMACIEN"
    | "ACCUEIL"
    | "COMPTABLE"
    | "DGTCP";

  @ApiProperty({
    required: false,
    enum: EnumUtilisateurStatut,
  })
  @IsEnum(EnumUtilisateurStatut)
  @IsOptional()
  @Field(() => EnumUtilisateurStatut, {
    nullable: true,
  })
  statut?: "Actif" | "Inactif";
}

export { UtilisateurUpdateInput as UtilisateurUpdateInput };
